dist: xenial
language: python
python:
  - "3.10"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    python: "nightly"


# command to install dependencies
install:
  - pip install pandas
  - pip install git+https://github.com/blampe/IbPy.git
# - pip install your_package


# command to run tests
script: cd tests && nosetests -v -v
